### ISSUE TITLE
Should we add license ?

### ISSUE THREAD

**Issue by githeap** [erwanp/qtplaskin#10]
Original Qtplaskin doesn't have license. For  later his projects (Bolos, Grempy) @aluque choosed LGPL2 , GPLv2 licenses.
- Should we have license?
- Should we ask Alejandro to add license to original Qtplaskin ?

**Comment by erwanp** [comment]
Good catch. I realized that strictly speaking, without a license on Alejandro's original code, we are allowed to fork it (under GitHub use conditions) but not to modify it ([see here](https://opensource.stackexchange.com/a/1721/15930)). 

- So we need to add license to the original Fork (and cherry-pick to this one). 

The choice is mainly between LGPL and BSD style licenses. We should probably stick to @aluque preference and go for LGPL. Version 3 is [is recommended](https://opensource.stackexchange.com/q/7387): over 2: 

> LGPLv3 is the current version of the GNU Lesser General Public License. LGPLv2.1 is an older version and not recommended by the Free Software Foundation for new projects anymore

If you agree, I can (or you can) create a PR to the original repository with LGPLv3.

**Comment by githeap** [comment]
Done (LGPLv3).
https://github.com/aluque/qtplaskin/commit/ae7c55271277b9cdd6bd609d8a5b955b8406611a
https://github.com/erwanp/qtplaskin/commit/93d5c2e192064463156444c77229e20417f61038
