### ISSUE TITLE
Fix packaging

### ISSUE THREAD

**Issue by erwanp** [erwanp/qtplaskin#11]
QtPlaskin original package could be deployed as a self-contained app. 

In the process of making it an installable Python package I did not ensure that QtPlaskin could still be packaged (this is discussed in [this discussion on the original repo](https://github.com/aluque/qtplaskin/pull/3)). According to @aluque that feature remains important for users:

> Regarding the packaging I found that some people used this software just because it was packaged so conveniently but I had to use some tricks to produce the self-contained distribution files.  I have no idea on whether the packaging libraries have improved since.

Before deploying to PyPi we should therefore fix that. 

@aluque used py2exe. However the package [is not actively maintained anymore](https://stackoverflow.com/a/6235314/5622825). We should therefore switch to [pyinstaller](https://www.pyinstaller.org/). 

@githeap what do you think?

### TODO list (from comments)

- [ ] we add qtplaskin logo and desktop file
- [ ] install script that copies it in respective places

**Comment by githeap** [comment]
Packaging QtPlaskin as self-contained app is very important, indeed. Especially for Windows users, I guess. We need to do it for  release version. I am Linux user and pypi package is what I want.  
I don't know how to fix packaging yet, but eventually we will do it.
At the moment I am looking at [Veusz](https://veusz.github.io/download/). We shall do something similar. 
As small improvement we can add qtplaskin logo and desktop file (for Linux users or shortcut for Windows) and install script that copies it in respective places (~/Desktop/ or ~/.local/share/applications).

**Comment by erwanp** [comment]
Hey @githeap  . I managed to package and generate a .exe on Windows with Pyinstaller. 
The procedure is detailed in `qtplaskin/cli.py`   (2 lines)

**Comment by erwanp** [comment]
Hey @githeap . Digging this out, but I think this was the latest change required before actually merging to Aluque's!  https://github.com/aluque/qtplaskin/pull/5 

What do you think is left ?  Does it fix #17  ??
