### ISSUE TITLE
bug in Pandas when reading files with 'Infinity'

### ISSUE THREAD

**Issue by githeap** [erwanp/qtplaskin#6]
By default this fork of QtPlaskin uses pandas.read_csv  function to speed up data loading.
ZdPlaskin is a Fortran code and uses "Infinity" to represent inf values in output text files.
There is an [issue #10065](https://github.com/pandas-dev/pandas/issues/10065) in Pandas with reading such files. Pandas read_csv interprets "Infinity" as a string, not a floating point value.

Untill  the issue #10065 is not resolved in Pandas, as a workaround, we fallback to old (slower) data import for datasets containing "Infinity"s. [a5b1559](https://github.com/erwanp/qtplaskin/commit/a5b1559393f5041686ae6956e66a3c71ed49ba90)   

**Update**: Add a very straightforward fix to Pandas [#28181](https://github.com/pandas-dev/pandas/pull/28181). Hope, someone will come up with smarter solution.  

 - [x] Get https://github.com/pandas-dev/pandas/pull/28181 be merged
-  [x] Wait for Pandas release
-  [x] Fix tests (remove `xfail`) 
-  [x] Update `setup.py` https://github.com/erwanp/qtplaskin/blob/1aeb4a7ec618a3be10447c8e18b7b03a6b2ecf69/setup.py#L48-L56

**Comment by githeap** [comment]
Add a very straightforward fix to Pandas [#28181](https://github.com/pandas-dev/pandas/pull/28181). Hope, someone will come up with smarter solution.

**Comment by githeap** [comment]
- [ ] Get https://github.com/pandas-dev/pandas/pull/28181 be merged
-  [ ] Wait for Pandas release
-  [ ] Update `setup.py` https://github.com/erwanp/qtplaskin/blob/1aeb4a7ec618a3be10447c8e18b7b03a6b2ecf69/setup.py#L48-L56

**Comment by erwanp** [comment]
Well done on getting it approved!

**Comment by githeap** [comment]
https://github.com/pandas-dev/pandas/pull/28181 was merged in [Pandas 1.0](https://github.com/pandas-dev/pandas/tree/v1.0.0)
