### ISSUE TITLE
Open/Save HDF5 files is broken in v1.1.1 

### ISSUE THREAD

**Issue by githeap** [erwanp/qtplaskin#8]
Get error trying to open HDF5 file. Save menu item not working. 
Fixed upstream (6eed2f9 84458e5 2eb0056). 
Still can't open files created by QtPlaskin in [ViTables](vitables.org) and [HDFView](https://www.hdfgroup.org/downloads/hdfview/).

**Comment by erwanp** [comment]
@githeap do still have this problem ?

**Comment by githeap** [comment]
ViTables 2.1 and HDFView 2.11 failed to open files created by QtPlaskin. But I was able to import data from the hdf5 file to Veusz and h5check(version 2.0 release 1) utility didn't find any problems. So I guess the file is OK. Closing.

**Comment by erwanp** [comment]
Perfect ! Btw, if you use JupyterLab as your IDE, I just discovered this nice HDF5 extension https://github.com/jupyterlab/jupyterlab-hdf5

**Comment by githeap** [comment]
Very nice, thanks!
